### ISSUE TITLE
When will the code for the paper be provided?

### ISSUE THREAD

**Issue by iHa0** [deezer/semi_perso_user_cold_start#1]
I'm very interested in this paper. I'd like to know if the code will be provided and when it will be provided. Thank you.

**Comment by GuillaumeSalhaGalvan** [comment]
Dear @iHa0,

Thanks for your interest!

Code and data will be online before the KDD conference (August 14th) for sure and, if possible, by the end of July.

I'll keep you informed.

Best,

Guillaume

**Comment by iHa0** [comment]
Thanks!

**Comment by leabriand** [comment]
Dear @iHa0,

Thanks for your interest!

Code and data are now available, do not hesitate to contact us again if you encounter any issue with it.

Best,

Léa
