### ISSUE TITLE
TT-SVD

### ISSUE THREAD

**Issue by Kasonreal** [deezer/semi_perso_user_cold_start#2]
Hey, can you explain how to get TT-SVD in detail, such as how to construct the track-track matrix? Thanks

**Comment by leabriand** [comment]
Hello Kasonreal,

Thanks for your message and interest in our project.

Our track-track matrix represents the PMI (Point Mutual information), that measures the association between two songs x and y by calculating the log of the ratio between their joint probability (the frequency in which they occur together) and their marginal probabilities (the frequency in which they occur independently). This measure is closely related to conditional probability, and can be interpreted as : Given a song x, what is the likelihood that the song y is observed in the same user profile or playlist?

To do that, we compute lists of tracks occurring in a same context (context being a playlist, album, list of favorites from a user profile...) and then compute the PMI between each pair of available tracks.

Do not hesitate if you have other questions.

**Comment by Kasonreal** [comment]
Thanks for your reply. I still have a detailed question. We consider all contexts and get a playlist TT matrix, an album TT matrix.... and then we concatenate these embeddings in each context? Or we caculate the PMI in all contexts and get only one TT matrix?

**Comment by leabriand** [comment]
Hello Kasonreal,

In our framework, we chose to have only one TT matrix that gathers the information from different contexts.
